# Google Fonts
google:
  fonts: https://fonts.googleapis.com/css?family=Titillium+Web:400,200italic,300,300italic,400italic,600,600italic,700,700italic,900,200|Cutive+Mono|Rasa:300,400,500,600,700

fontawesome:
  font: https://use.fontawesome.com/ad93da429e.js

# Social Links
social:
  github: https://github.com/matt-whitaker
  linkedin: https://www.linkedin.com/in/whitakermatt
  twitter: https://twitter.com/__mattwhitaker

# Nav Links
links:
  - title: About
    href: /about
  - title: Archive
    href: /archive
  - title: Projects
    links:
      - title: Project 1
        href: /posts/hello-world
      - title: Disjointed Thinking
        href: /work/disjointed-thinking
      - title: Want 2 Hack
        href: /work/want-2-hack
      - title: More...
        href: /work
  - title: Photos
    href: /photos

# Homepage Highlights
highlights:
  - href: about
    icon:
  - href: work
    icon:
  - href: work/disjointed-thinking
    icon:

homepage:
  image: /images/seattle-1.png
  blurb: Homebrewed in Seattle, my ramblings <br/>on web development, the Pacific Northwest, <br/>and the occasional adventure.

archive:
  image: /images/stone-pathway-wallpaper-1.jpg
  title: Archive
