# Google Fonts
google:
  fonts: https://fonts.googleapis.com/css?family=Titillium+Web:400,200italic,300,300italic,400italic,600,600italic,700,700italic,900,200|Cutive+Mono|Rasa:300,400,500,600,700

# Social Links
social:
  github: https://github.com/matt-whitaker
  linkedin: https://www.linkedin.com/in/whitakermatt
  twitter: https://twitter.com/__mattwhitaker

# Nav Links
links:
  - title: About
    href: /about.html
  - title: Archive
    href: /archive
  - title: Work
    links:
      - title: Project 1
        href: /posts/hello-world
      - title: Disjointed Thinking
        href: /work/disjointed-thinking.html
      - title: Want 2 Hack
        href: /work/want-2-hack.html
      - title: More...
        href: /work.html

# Homepage Highlights
highlights:
  - about.html
  - work.html
  - work/disjointed-thinking.html

homepage:
  image: /images/seattle-1.png
  image_offset: 0 20%
#  image_size: 100%
  blurb: Homebrewed in Seattle, my ramblings <br/>on web development, the Pacific Northwest, <br/>and the occasional adventure.

archive:
  image: /images/stone-pathway-wallpaper-1.jpg
  image_offset: 0 20%
  title: Archive
