# Google Fonts
google:
  fonts: https://fonts.googleapis.com/css?family=Titillium+Web:400,200italic,300,300italic,400italic,600,600italic,700,700italic,900,200|Cutive+Mono|Rasa:300,400,500,600,700

# Social Links
social:
  github: https://github.com/matt-whitaker
  linkedin: https://www.linkedin.com/in/whitakermatt
  twitter: https://twitter.com/__mattwhitaker

# Nav Links
links:
  - title: About
    href: /about.html
  - title: Archive
    href: /archive
  - title: Work
    links:
      - title: Project 1
        href: /wonderful-time.html
      - title: Link 2
        href: /posts/hello-world
      - title: Link 3
        href: /posts/hello-world
      - title: More...
        href: /all-work.html
